---
title: OpenVox Documentation
description: Documentation for various OpenVox Projects.

lang: en-US
timezone: UTC

theme: jekyll-vitepress-theme
plugins:
  - jekyll-vitepress-theme

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter_opts:
    block:
      line_numbers: false

jekyll_vitepress:
  branding:
    logo:
      default: 'https://github.com/voxpupuli/logos/blob/master/images/OpenVox/Sticker/HexagonSticker.svg?raw=true'
      alt: OpenVox Automation Framework
  # Disabled as it adds extra size to generated HTML pages.
  copy_page:
    enabled: false

collections_dir: docs
collections:
  openbolt_latest:
    output: true
    permalink: '/openbolt/latest/:path.html'
  openbolt_5x:
    output: true
    permalink: '/openbolt/5.x/:path.html'

  openfact_latest:
    output: true
    permalink: '/openfact/latest/:path.html'
  openfact_5x:
    output: true
    permalink: '/openfact/5.x/:path.html'

  openvoxdb_latest:
    output: true
    permalink: '/openvoxdb/latest/:path.html'
  openvoxdb_8x:
    output: true
    permalink: '/openvoxdb/8.x/:path.html'
