---
name: Automatically publish new content

on:
  push:
    paths:
      - '_config.yml'
      - 'index.md'
      - '_data/**/*'
      - '_includes/**/*'
      - '_layouts/**/*'
      - 'docs/**/*'

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    with:
      ref: '${{ github.sha }}'
    permissions:
      contents: read
      packages: write

  deploy:
    needs: build
    uses: ./.github/workflows/deploy.yaml
    with:
      tag: '${{ needs.build.outputs.tag }}'
    secrets: inherit
